project 'Carko.xcodeproj'

use_frameworks!
inhibit_all_warnings!

platform :ios, '10.0'

def shared_pods
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage', '~> 1.0'
  pod 'Stripe'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'NohanaImagePicker'
  # We need to remove this
  pod 'SCLAlertView'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'Carko' do
  pod 'Firebase/Crash'
  shared_pods
end

target 'CarkoProduction' do
  shared_pods
end

target 'CarkoTests' do
    pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
    pod 'OHHTTPStubs/Swift' # Adds the Swiftier API wrapper too
    shared_pods
end

target 'CarkoUITests' do
    shared_pods
end
