project 'Carko.xcodeproj'
use_frameworks!

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Carko' do
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage', '~> 1.0'
  pod 'Stripe'
  pod 'Alamofire'
  pod 'ARNTransitionAnimator', '2.0.3'

  target 'CarkoTests' do
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Stripe'
    pod 'Alamofire'

    pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
    pod 'OHHTTPStubs/Swift' # Adds the Swiftier API wrapper too
  end

  target 'CarkoUITests' do
    inherit! :search_paths
  end
end
