project 'Carko.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Carko' do
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase'
  pod 'Firebase/Database'

  target 'CarkoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarkoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
